install:
    - sudo apt-get install -y --force-yes apache2
    - sudo a2enmod rewrite
    - sudo cp .human/virtual-host.conf /etc/apache2/sites-available/default
    - sudo a2ensite default
    - sudo service apache2 reload
